name: limewyre
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^9.0.0
  pinput: ^5.0.1
  intl: ^0.20.2
  get: ^4.7.2
  google_fonts: ^6.3.3
  loading_animation_widget: ^1.3.0
  pin_code_fields: ^8.0.1
  iconsax: ^0.0.8
  amplify_storage_s3: ^2.6.1
  amplify_flutter: ^2.6.1
  amplify_api: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  hive_flutter: ^1.1.0
  shared_preferences: 
  url_launcher: ^6.3.2
  flutter_linkify: ^6.0.0
  receive_sharing_intent: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
